
    create table automobile (
        cilindrata integer,
        id integer not null,
        numero_porte integer,
        targa varchar(10) not null unique,
        primary key (id)
    );

    create table bici (
        id integer not null,
        is_pieghevole boolean,
        numero_rapporti integer,
        tipo_freno varchar(30),
        tipo_sospensione varchar(30),
        primary key (id)
    );

    create table categoria (
        categoria varchar(255) not null,
        tipo_veicolo varchar(255) not null,
        primary key (categoria, tipo_veicolo)
    );

    create table categorie_automobili (
        segmento char(1),
        categoria varchar(255) not null,
        primary key (categoria)
    );

    create table moto (
        cilindrata integer,
        id integer not null,
        targa varchar(10) not null unique,
        primary key (id)
    );

    create table tipi_alimentazione_motorizzati (
        tipo varchar(255) not null,
        primary key (tipo)
    );

    create table tipo_freno (
        tipo_freno varchar(255) not null,
        primary key (tipo_freno)
    );

    create table tipo_sospensione (
        tipo_sospensione varchar(255) not null,
        primary key (tipo_sospensione)
    );

    create table tipo_alimentazione (
        tipo_alimentazione varchar(255) not null,
        tipo_veicolo varchar(255) not null,
        primary key (tipo_alimentazione, tipo_veicolo)
    );

    create table veicolo (
        anno_produzione integer not null,
        id integer generated by default as identity,
        numero_ruote integer not null,
        alimentazione varchar(30) not null,
        colore varchar(30) not null,
        categoria varchar(50) not null,
        marca varchar(50) not null,
        modello varchar(50) not null,
        tipo_veicolo varchar(50) not null,
        primary key (id)
    );

    alter table if exists automobile 
       add constraint FKb14xqlpgteyrp5tpgq8ncmmvo 
       foreign key (id) 
       references veicolo;

    alter table if exists bici 
       add constraint FKbwomtnan9xt4w1ovsf9sod7y1 
       foreign key (id) 
       references veicolo;

    alter table if exists moto 
       add constraint FKhg6x1bil1w6nnp4fxlwebfc3l 
       foreign key (id) 
       references veicolo;
