
    create table automobile (
        cilindrata integer,
        id integer not null,
        numero_porte integer,
        targa varchar(10) not null unique,
        primary key (id)
    );

    create table bici (
        id integer not null,
        is_pieghevole boolean,
        numero_marce integer,
        tipo_freno varchar(30),
        tipo_sospensione varchar(30),
        primary key (id)
    );

    create table moto (
        cilindrata integer,
        id integer not null,
        targa varchar(10) not null unique,
        primary key (id)
    );

    create table veicolo (
        anno_produzione integer not null,
        id integer generated by default as identity,
        numero_ruote integer not null,
        alimentazione varchar(30) not null,
        colore varchar(30) not null,
        categoria varchar(50) not null,
        marca varchar(50) not null,
        modello varchar(50) not null,
        tipo_veicolo varchar(50) not null,
        primary key (id)
    );

    alter table if exists automobile 
       add constraint FKb14xqlpgteyrp5tpgq8ncmmvo 
       foreign key (id) 
       references veicolo;

    alter table if exists bici 
       add constraint FKbwomtnan9xt4w1ovsf9sod7y1 
       foreign key (id) 
       references veicolo;

    alter table if exists moto 
       add constraint FKhg6x1bil1w6nnp4fxlwebfc3l 
       foreign key (id) 
       references veicolo;
